---
- name: "Install from sources"
  ansible.builtin.include_tasks:
    file: install_src.yml
  when: kibana_install_method == "src"

- name: "Install from repo"
  ansible.builtin.include_tasks:
    file: install_repo.yml
  when: kibana_install_method == "repo"

- name: "Copy Kibana configuration."
  ansible.builtin.template:
    src: "kibana.yml.j2"
    dest: "{{ kibana_config_file_path }}"
    owner: root
    group: root
    mode: "0644"
  notify: Restart kibana
