---
- name: "Check for kibana folder"
  stat:
    path: '/usr/share/kibana/'
  changed_when: false
  register: kibana_install

- when: not kibana_install.stat.exists or kibana_force_install|bool
  block:
    - name: Ensure dependencies are installed.
      package:
        name:
          - apt-transport-https
          - gnupg2
        state: present
    
    - name: Add Elasticsearch apt key.
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present
    
    - name: Add Kibana repository.
      apt_repository:
        repo: 'deb https://artifacts.elastic.co/packages/{{ kibana_version }}/apt stable main'
        state: present
        update_cache: true

    - name: Install Kibana.
      package:
        name: "{{ kibana_package }}={{ kibana_version_else }}"
        state: present
        force: yes
    
    - name: Ensure Kibana is started and enabled at boot.
      service:
        name: kibana
        state: started
        enabled: true

- name: Copy Kibana configuration.
  template:
    src: "{{ kibana_config_template }}"
    dest: "{{ kibana_config_file_path }}"
    owner: root
    group: root
    mode: 0644
  notify: restart kibana
